<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>true</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <AssemblyName>STS2WebBrowser</AssemblyName>
    <RootNamespace>STS2WebBrowser</RootNamespace>
    <Sts2Dir Condition="'$(Sts2Dir)' == ''">$(MSBuildProjectDirectory)</Sts2Dir>
    <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
    <IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsOSX>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsWindows)' == 'true'">
    <GamePlatform>windows_x86_64</GamePlatform>
    <DirectorySeparator>\\</DirectorySeparator>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsLinux)' == 'true'">
    <GamePlatform>linux_x86_64</GamePlatform>
    <DirectorySeparator>/</DirectorySeparator>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsOSX)' == 'true'">
    <GamePlatform>osx_universal</GamePlatform>
    <DirectorySeparator>/</DirectorySeparator>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="GodotSharp" HintPath="$(Sts2Dir)\data_sts2_$(GamePlatform)\GodotSharp.dll" Private="false" Condition="Exists('$(Sts2Dir)\data_sts2_$(GamePlatform)\GodotSharp.dll')" />
    <Reference Include="sts2" HintPath="$(Sts2Dir)\data_sts2_$(GamePlatform)\sts2.dll" Private="false" Condition="Exists('$(Sts2Dir)\data_sts2_$(GamePlatform)\sts2.dll')" />
    <Reference Include="0Harmony" HintPath="$(Sts2Dir)\data_sts2_$(GamePlatform)\0Harmony.dll" Private="false" Condition="Exists('$(Sts2Dir)\data_sts2_$(GamePlatform)\0Harmony.dll')" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="**/*.user" />
  </ItemGroup>
</Project>
